### ISSUE TITLE
Not abl to add function call to render

### ISSUE THREAD

**Issue by wpeereboom** [RangerMauve/react-native-square-grid#6]
When using :
`<SquareGrid columns={4} rows={false} items={this.sounds} renderItem={this.displayBlock} />`

I would like to use a function in the displayBlock method:
`
displayBlock(item) {
      return (
      <TouchableHighlight style={{ margin: 10 }} key={item.key} onPress={this._onItemPress(item.file)} underlayColor="white">
       <View style={[ styles.square, { backgroundColor: this.getRandomColor() }]} ><Text></Text></View>
       </TouchableHighlight>
     );
    }
`

I receive error:
TypeError: this._onItemPress is not a function. (In 'this._onItemPress(item.file)', 'this._onItemPress' is undefined)

Is this due to the way you render the grid?

**Comment by RangerMauve** [comment]
@wpeereboom I think the issue is that you're losing the `this` context when you pass the function as a prop. Try using `renderItem={this.displayBlock.bind(this)}`

**Comment by wpeereboom** [comment]
Great thanks, working!
